BudgetCategories = {'Furnishing': ['IKEA LTD', 'IKEA UK', 'SWAROVSKI', 'HOMESENSE'], 
                    'Fuel':['Motor Fuel', 'WELDALE', 'PARKING', 'FUEL', 'BP London Road', 'BENSONS SERVICE STATION',
                            'MFG SHINFIELD', 'Airchina', 'SONNING CUTTING FILLING READING' ],
                    'Department Stores':['TEMU'], 
                    'Travel':['GWR', 'AIRCHINA'],
                    'Restaurants, Bars & Cafés':['A BIT OF STICK', 'WAGAMAMA', 'JOHNNY SHAKE', 'STARBUCKS', 'CAFFE NERO', 'Toby Carvery', 'MCDONALDS', 'MCDONALD', 'BURGER KING', 'SUBWAY', 'ITSU', 
                                                 'BONFIRE THE BARBICAN', 'MASTER BAO', 'TACO BELL', 'AUNTIE ANNES', 'YOGOO', 'ZETTLE', 'DOMINOS'], 
                    'Groceries':['ASDA', 'CMART', 'TESCO', 'WM MORRISONS STORES', 'M&S', 'WH SMITH', 'COSTA', 'Dominos', 'MY FOOD','Costco Wholesale', 'COSTCO ONLINE',
                                'LIDL', 'SAINSBURY', 'ALDI', 'SEOUL PLAZA', 'HONEY and GHEE'], 
                    'Communication':[],
                    'Clothing':['TK MAXX', 'PRIMARK' 'LULULEMON', 'Bicester Village', 'CLARKS', 'Michael Kors', 'Michael Kors', 'COACH STORES', 'DONNA KARAN', 
                                'SPORTSDIRECT', 'ESTEE LAUDER', 'OCCITANE LTD', 'BURBERRY', 'UGG', 'LULULEMON'],
                    'Personal Care':['SP ROCCABOX', 'SHISEIDO', 'CLARINS'],
                    'AMAZON':['AMAZON.CO.UK'],
                    'Medical & Healthcare':['BOOTS THE CHEMIST', 'BOOTS THECHEMIST'],
                    'Computer Supplies':['HPI INSTANT INK', 'APPLE.COM'],
                    'Kids':['2VAA051195035', 'Eyesite Opticians', 'GYMFINITY KIDS', 'HILLSIDE', 'HOBBYCRAFT', 'WATERSTONES', 'Max Spielmann', 
                            'SUSAN DAUGHTREY', 'POP MART', 'APPLE STORE', 'OZONERINK'],
                    'Others':[]}